benchmarks/analyze_sharegpt.py
run_server.py

Remove personal information:
- Personal ldap
- Personal file path

Remove personal information

---

README.md
install_everything.sh

Here are fixes:
- Go back the main dir 
- Install main project
- Clear duplicated install in readme

Fix install_everything

---

run_interactive.py

This PR refactor current run_interactive.py, below are the changes:
- Streaming decode text, remove all output text when decode finished 
- Support multiple prompts
- Support end tokens and max_output_length stop instead of run 100 steps
- A random slot instead of 0 slot
- Enable profiler

Refactor interactive

---

jetstream_pt/third_party/llama2/generation_original.py
tests/test_llama_e2e.py

The purpose of this PR is testing the E2E accuracy between Jetstream engine inference and original llama inference. Below are tests:
- test_llama_e2e.  original llama inference 10 steps decode **vs** jetstream engine 10 steps
- test_original_llama2_seed.   original llama inference 10 steps with different seed
- test_jetstream_llama2_seed. jetstream engine 10 with different seed
- test_llama_e2e_two_addtional_tokens.  Same prefix as test_llama_e2e, add two additional tokens in prompts.  
-  test_llama_e2e_four_addtional_tokens.  Same prefix as test_llama_e2e, add four additional tokens in prompts.

Add llama end to end test with jetstream engine 

---

.github/workflows/unit_tests.yaml

This PR enable pyink indentation and line length check. Please use pyink --pyink-indentation 2 --line-length 80  to format the file before sending out the new PR.

Enable pyink check

---

.github/workflows/unit_tests.yaml

Google internal use 2 space as indentation, to keep engineer less effort on code style, change this to same indentation requirement as google internal.

Use 2 space as indentation

---

jetstream_pt/config.py

After this PR:
Your code has been **rated at 9.94/10**
************* Module jetstream_pt.config
config.py:19:0: C0116: Missing function or method docstring (missing-function-docstring)
config.py:19:0: R0913: Too many arguments (8/5) (too-many-arguments)
config.py:29:11: W0613: Unused argument 'a' (unused-argument)
------------------------------------------------------------------

Clean up config.py

---

tests/test_jax_torch.py

After this PR:
Your code has been **rated at 8.95/10**
************* Module tests.test_jax_torch
test_jax_torch.py:9:0: C0115: Missing class docstring (missing-class-docstring)
test_jax_torch.py:11:2: C0116: Missing function or method docstring (missing-function-docstring)
test_jax_torch.py:30:2: C0116: Missing function or method docstring (missing-function-docstring)
test_jax_torch.py:6:0: C0411: standard import "unittest" should be placed before third party imports "torch", "torch_xla2", "jax", "jax.numpy" (wrong-import-order)
-----------------------------------

Cleanup test_jax_torch

---

tests/.pylintrc
tests/test_model_impl.py

After this PR:
Your code has been **rated at 10.00/10** 
Your code has been **rated at 6.79/10**
test_model_impl.py:49:0: C0301: Line too long (132/100) (line-too-long)
test_model_impl.py:50:0: C0301: Line too long (131/100) (line-too-long)
test_model_impl.py:30:0: C0115: Missing class docstring (missing-class-docstring)
test_model_impl.py:32:2: C0116: Missing function or method docstring (missing-function-docstring)
test_model_impl.py:79:43: W0212: Access to a protected member _elem of a client class (protected-access)
test_model_impl.py:90:36: W0212: Access to a protected member _elem of a client class (protected-access)
test_model_impl.py:89:4: W0612: Unused variable 'batch' (unused-variable)
test_model_impl.py:109:2: C0116: Missing function or method docstring …

Fix test_model_impl lint

---

tests/test_quantization.py

After this PR:
Your code has been **rated at 8.00/10**
************* Module tests.test_quantization
test_quantization.py:24:0: C0115: Missing class docstring (missing-class-docstring)
test_quantization.py:30:2: C0116: Missing function or method docstring (missing-function-docstring)
test_quantization.py:16:0: C0411: standard import "unittest" should be placed before third party import "jax" (wrong-import-order)
test_quantization.py:21:0: C0412: Imports from package jax are not grouped (ungrouped-imports)
test_quantization.py:18:0: W0611: Unused quantize imported from jetstream_pt (unused-import)
-----------------------------------

Fix test quantization lint check

---

tests/jax_test.py
tests/test_quantization.py

After this PR:
------------------------------------------------------------------
Your code has been **rated at  5.73/10**
jax_test.py:21:0: C0116: Missing function or method docstring (missing-function-docstring)
jax_test.py:23:2: W0621: Redefining name 'f' from outer scope (line 200) (redefined-outer-name)
jax_test.py:35:2: W0621: Redefining name 'A' from outer scope (line 174) (redefined-outer-name)
jax_test.py:24:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
jax_test.py:35:2: C0115: Missing class docstring (missing-class-docstring)
jax_test.py:40:4: C0116: Missing function or method docstring (missing-function-docstring)
jax_test.py:35:2: R0903: Too few public …

Fix quantizaiton and jax lint check

---

run_interactive.py

After this PR:
Your code has been **rated at 5.39/10**
************* Module jetstream-pytorch.run_interactive
run_interactive.py:119:0: C0301: Line too long (888/100) (line-too-long)
run_interactive.py:120:0: C0301: Line too long (429/100) (line-too-long)
run_interactive.py:121:0: C0301: Line too long (387/100) (line-too-long)
run_interactive.py:122:0: C0301: Line too long (333/100) (line-too-long)
run_interactive.py:32:0: E1101: Module 'absl.logging' has no 'getLogger' member (no-member)
run_interactive.py:75:0: C0116: Missing function or method docstring (missing-function-docstring)
run_interactive.py:80:2: W0612: Unused variable 'max_target_length' (unused-variable)
run_interactive.py:100:0: C0116: Missing function or method …

Fix run_interactive lint check

---

run_server.py

After this PR:
Your code has been **rated at 8.82/10**
************* Module jetstream-pytorch.run_server
run_server.py:110:3: W0511: TODO: Add grpc credentials for OSS. (fixme)
run_server.py:85:0: C0116: Missing function or method docstring (missing-function-docstring)
run_server.py:24:0: C0411: third party import "jetstream.core.config_lib.ServerConfig" should be placed before first party import "jetstream_pt"  (wrong-import-order)
run_server.py:24:0: C0412: Imports from package jetstream are not grouped (ungrouped-imports)
-----------------------------------
Your code has been rated at 8.82/10

Fix run_server lint check

---

run_interactive.py

JetStream PR 40 removed  mix_decode 
function (https://github.com/google/JetStream/commit/a0df320cb4a720bf123e2579973034628dbe3344#diff-1f6a127e88897ae4bd1191a2b3609a1507a9e667fbc22dda89f67b26653e99eb). 
Pytorch engine is depending on mix_decode and use it to do stream decode. Comment this part of code to unblock pytorch engine interactive run.

Comment broken function to unblock interactive run after JetStream api change

---

run_interactive.py

To fix this index error
warnings.warn("Some donated buffers were not usable:"
---- Streaming decode started on #slot32.
new_pos Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>
cache_seq_len 2048
Traceback (most recent call last):
File "/home/bbahl/jetstream-pytorch/run_interactive.py", line 168, in <module>
app.run(main)
File "/home/bbahl/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
_run_main(main, args)
File "/home/bbahl/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
sys.exit(main(argv))
File "/home/bbahl/jetstream-pytorch/run_interactive.py", line 146, in main
token_id = slot_tokens[slot, 0].item()
File "/home/bbahl/.local/lib/python3.10/site-packages/jax/_src/array.py", line 348, in __getitem__
return …

Pick a slot from 0 to batch_size-1 during run_interactive.py

---

benchmarks/prefill_offline.py

**Context:**
For disaggregation serving, I would like to know what are max performance for prefill only. Below are example of questions: 
1. How many prefill we can do per seconds
2. What are the bottleneck
3. what the percentage real performance vs in theory one 
4. If compute bound, how could we improve it
**Benefits:** 
This PR collect latency metrics of prefill for different token size (from 16 to 32768), it help me to explore above questions and also help other engineer who would like do similar analysis in future. 
**Results for llama2 7B:** 
---- execute First Token: 737
---- execute time: 0.0057392120361328125 for token_len: 16
---- execute First Token: 13
---- execute time: 0.005574226379394531 for token_len: 32
---- execute First Token: 3634
---- execute time: …

Add prefill only benchmark for different token length

---

default_shardings/gemma.yaml
default_shardings/llama-2.yaml
jetstream_pt/engine.py
jetstream_pt/environment.py
jetstream_pt/layers.py
jetstream_pt/third_party/gemma/__init__.py
jetstream_pt/third_party/gemma/config.py
jetstream_pt/third_party/gemma/model.py
jetstream_pt/third_party/gemma/model_original.py
jetstream_pt/third_party/gemma/tokenizer.py
jetstream_pt/third_party/llama/generation_original.py
jetstream_pt/third_party/llama/model_args.py
jetstream_pt/third_party/llama/model_exportable.py
run_interactive.py
run_server.py
scripts/jax_experiments.py
tests/helpers.py
tests/test_engine.py
tests/test_llama_e2e.py
tests/test_model_impl.py

Changes include:
* refactor engine to not use hardcoded sharding annotations; but instead read from a file.
* Replace GemmaAttention class used in Gemma with layers.Attention: they seems to be doing the same thing.
* added model_name arg to create_engine
Run interactive and run server both works with random weights.

Add gemma support

---

jetstream_pt/ray_engine.py
jetstream_pt/ray_worker.py
run_interactive_multiple_host.py

This PR add gemma and update recent changes to multiple host. In the end, the multiple host and single host should share as much code as possible after we finished multiple host support, but right now the code are diverged.

Add gemma and update recent changes to  multiple host

---

benchmarks/analyze_sharegpt.py
benchmarks/run_offline.py
jetstream_pt/engine.py
jetstream_pt/environment.py
jetstream_pt/layers.py
jetstream_pt/third_party/gemma/model.py

For Gemma 2B we need to change the shardings because the dimension we usually shard, `num_kv_heads` happens to be 1 for Gemma 2B. So we pick a different one to shard.

Enable Gemma 2B

---

jetstream_pt/layers.py

70B llama is failing now since it uses GQA

Fix attention kernel of GQA use case

---

jetstream_pt/engine.py
run_server.py

Fix sharding config file name bug. Two fixed:
1. Current code uses llama2 or llama3 as file name, but the sharding yaml file name is llama. 
2. Engine has logic to handle none sharding_config, removed the duplicated logic in run server

Fix sharding config file name bug

---

.github/workflows/unit_tests.yaml
.gitignore
.gitmodules
install_everything.sh
pyproject.toml
run_interactive.py

* Make deps into submodule - the hash of particular submodule is stored in git's database
* Made run_interactive.py with tiny to a CI
* fix some issues with run_interactive

Move deps to git submodule

---

run_interactive.py

Leverage token_utils to process the result tokens.  This simplify the logic of run_interactive.py and make sure the result are consistency from run_interactive vs online.

Leverage tokens_utils to process result tokens

---

install_everything.sh

This PR fix the flax and ray dependencies issues. 
**Import error:** 
>  ImportError: cannot import name 'linear_util' from 'jax' (/home/username/.local/lib/python3.10/site-packages/jax/__init__.py)
**Reasons:**
The linear_util module was deprecated in JAX v0.4.16 and completely removed in JAX v0.4.24. Flax with older versions that still try to import linear_util

Fix flax and ray dependencies

---

jetstream_pt/engine.py
jetstream_pt/ray_worker.py
jetstream_pt/torchjax.py
run_interactive_multiple_host.py
tests/test_quantization.py

This PR add below changes:
1: move torch_xla2.default_env() to function. jax_mode = torch_xla2.default_env() block jax multiple controller in init state
2: ray engine create is different than default run server one, it will have prefill and decode engines later 
3: removed duplciated JetEngineEnvironment 
4: Not support shard_on_batch and ragged attention in ray multiple for now

Fix ray conflict changes 

---

README.md
convert_checkpoints.py

Before this PR, the config logic in `convert_checkpoints.py` is broken, only quantized checkpoint can be generated.
After the fix:
- Use `--quantize_weights` to control if checkpoint will be quantized.
- Use `--quantize_type` to specify the quantization type, only effective when `--quantize_weights` is true.

Fix convert script cannot generate bf16 weights

---

install_everything.sh
jetstream_pt/ray_engine.py
jetstream_pt/ray_worker.py
run_interactive_disaggregated.py

This PR enable pytorch engine disaggregated serving on multiple TPU POD slices. 
1.  Engine do prefill in one POD slice and do decode in another POD slice 
2. Transfer prefill result from one POD slice to another POD slice 
3. Load weight and sharding in multiple host on multiple POD slice
4. Compute meaningful decode result 
1. Disaggregated serving, here is the logs (tpu-vm-1 as decode engine):
> ---- Do prefill in prefill engine pod_slice_name: tpu-vm-2
> ---- Transfer prefill result to decode engine pod_slice_name: tpu-vm-1
> ---- Do insert in decode engine pod_slice_name: tpu-vm-1
2. Correct result compared with interleave serving 
Command: 
`python /home/{user}/jetstream-pytorch/run_interactive_disaggregated.py --size=7b --batch_size=1 --is_disaggregated=True --num_hosts=8 …

Ray Disaggregated Serving MVP

---

jetstream_pt/ray_engine.py
jetstream_pt/ray_worker.py
run_server_with_ray.py

Enable jax profiler server in run with ray. This enable we can do profile through Tensorboard without manually copy large profile files.

Enable jax profiler server in run with ray

---

README.md

Add readme interleave multiple host

Add for readme interleave multiple host with ray

---

convert_checkpoints.py

Fixes https://github.com/google/jetstream-pytorch/issues/115

Fix conversion bug

---

jetstream_pt/ray_engine.py
run_interactive_disaggregated.py
run_server_with_ray.py

Integrate disaggregated serving with JetStream. Below are highlight of changes:
1. Return tuple list of prefill engine and decode engine when disaggregated serving enabled, otherwise return a interleave engine
2. Hard code the chips for engine and chips per host now, will change it in near future

Integrate disaggregated serving with JetStream

---

install_everything.sh
install_everything_gpu.sh
run_server.py
tests/test_model_impl.py

Need to update xla pin to https://github.com/pytorch/xla/pull/7307 as otherwise it will error on GPUs.

make sure GPU works

---

jetstream_pt/third_party/llama/model_exportable.py

All the TransformerBlock layer share a giant scope name, it's hard to debug and check details of profile for a layer. This PR adding layer id in scope for each TransformerBlock layer, there is scope boundary between layers, engineer can go to individual layer to check profile details.

Add layer id in scope for each TransformerBlock layer

---

run_server.py

- passes profiler arguments to server launch as optional
- uses instructions provided [here](https://github.com/google/JetStream/blob/main/docs/profiling-with-jax-profiler-and-tensorboard.md) for how to port forward from remote to local browser
example:
```
python run_server.py 
--size=8b 
--batch_size=1 
--max_cache_length=128 
--quantize_weights=false  
--quantize_kv_cache=true 
--checkpoint_path=".../models" 
--tokenizer_path=".../models/tokenizer.model" 
--model_name=llama-3
--sharding_config="default_shardings/llama.yaml"
--temperature=0.5
--sampling_algorithm="weighted"
--enable_jax_profiler=True # defaults to port 9999
```
Test when enabled on v5e-1:
```
python deps/JetStream/jetstream/tools/requester.py \
--tokenizer ".../models/tokenizer.model" 
Proxy backend support is not added …
```

add enable jax profiler to run_server

---

run_server.py
tests/test_run_server.py

creates unit tests for run_server.py
Tests to provide some coverage to important launch scripts, with a focus on default configuration instantiation.
1. test sets different model_name params to instantiate default configs. Provides some coverage for unintended default changes.
2. this test ensures the server run  and wait for termination methods are called exactly once.

Add server tests

---

jetstream_pt/ray_worker.py

The cache manager recently added a parameter for env: https://github.com/google/jetstream-pytorch/blob/main/jetstream_pt/cache_manager.py#L94
But this is not passed in the Ray worker: https://github.com/google/jetstream-pytorch/blob/main/jetstream_pt/ray_worker.py#L353
This will cause the Ray process to crash when the cache manager tries to access self.env: https://github.com/google/jetstream-pytorch/blob/main/jetstream_pt/cache_manager.py#L106

Fix exception in ray_worker

---

convert_checkpoints.py
install_everything.sh
jetstream_pt/cli.py
jetstream_pt/engine.py
jetstream_pt/environment.py
jetstream_pt/fetch_models.py
jetstream_pt/layers.py
jetstream_pt/model_base.py
jetstream_pt/quantize_model.py
jetstream_pt/ray_worker.py
jetstream_pt/third_party/llama/model_exportable.py
jetstream_pt/torchjax.py
tests/test_hf_names.py
tests/test_quantization.py

Each model that needs to support alternative names (i.e. HF) names, inherit from ModuleBase. and defines HF names for it's parameters and submodules, via `self.hf_name` call.
ModuleBase defines `get_hf_names_to_real_name` that returns hf name to the model name; which the loader can then use to remap the names before loading.
Modules inside of layers.py (Attention) should inherit ModuleBase but shouldnt define any mappings, because it might be used in different models. Let those models to define the mapping to it's corresponding HF checkpoints.
1. if a flag is used on only one file, define it there.
2. if a flag is for something internal for testing (like use_qkv); 
3. if a flag is likely to be modified for unit test; then use the Environment to store it.
4. Try to have least amount of …

prototyping better UX

---

benchmarks/mixtral_offline.sh
benchmarks/run_offline.py
mlperf/README.md
mlperf/backend.py
mlperf/benchmark_run.sh
mlperf/dataset.py
mlperf/install.sh
mlperf/main.py
mlperf/mlperf.conf
mlperf/start_server.sh
mlperf/user.conf
mlperf/warmup.py

TODOS:
* try llama70.
* Modify backend.py to use asyncio instead of threadpool.
===
All python files are copied from https://github.com/tpu-inference/inference_mlperf4.1/tree/mixtral_loadgen/language/mixtral-8x7b
and shell scripts adapted from https://docs.google.com/document/d/112oYiFB_hkbb0_Kfcm0iDaDVcsq3JwLYprc_1zh_FCo/edit?tab=t.0
With the following changes:
* dont install mlperf loadgen from source but install from pip instead
* install scripts / run scripts respects virtualenv
* remove 'warmup' feature from loadgen scripts; but do it in a separate script intead.
*

Add mlperf benchmark scripts in-tree.

---

jetstream_pt/layers.py

XLA generate a more optimized graph in this way
Before the change, some collective ops are working on int32 mamtul, with this change those becomes bf16 (Expected). Latency is improved by ~10% compared with per-channel int8 weight only quant baseline, on llama2 70B BS=96

Set accumulate type to bf16 in activation quant

---

jetstream_pt/ray_worker.py

All the ray worker returned array should be np array.

Return np instead of jax array for prefill result tokens

---

jetstream_pt/layers.py
jetstream_pt/third_party/llama/model_exportable.py
jetstream_pt/third_party/mixtral/model.py

Simple fix of the typo enbedding that should be spelled embedding.

Correct typo enbedding -> embedding

---

README.md
install_everything.sh
run_interactive_multiple_host.py

Recent xla2 change call jax.devices() in init state, all the TPU been used by head, it caused all the worker throw below errors:
> RuntimeError: Unable to initialize backend 'tpu': ABORTED: The TPU is already in use by process with pid .. 
I submitted https://github.com/pytorch/xla/pull/7769 to fix the xla2 initialization issue. This PR applied the xla2 fix and updated the readme.

Fixed exhausted bug between head and workers

---

jetstream_pt/cache_manager.py
jetstream_pt/page_attention_manager.py
tests/test_kv_cache_manager.py
tests/test_page_attention.py

This PR adds two classes, fundamental for page attention in JetStream:
PageAttentionManager:
This class manages and frees page resources, calculates page metadata, and supports cache insertion.
PageKVCacheGenerate:
This class updates decode caches in a page-attention format. Unlike the standard LLM KV cache shape ([batch_size, num_heads, seq_len, head_dim]), PageKVCache uses the shape [num_heads, total_num_pages, page_size, head_dim].

Add page attention manager and kvcache manager

---

benchmarks/basic_ops.py

Output on v5litepod-8:
```
Number of devices:  8
bfloat16         Matmul replicated:     438.17 ms        sizes: ('2048.0 MiB', '2048.0 MiB')
bfloat16         Matmul sharded colrow:         108.891 ms       sizes: ('2048.0 MiB', '2048.0 MiB')
bfloat16         matmul sharded rowcol:         76.6386 ms       sizes: ('2048.0 MiB', '2048.0 MiB')
bfloat16         all_gather:    68.3381 ms       sizes: ('2048.0 MiB',)
bfloat16         all_reduce:    8.25386 ms       sizes: ('2048.0 MiB',)
bfloat16         Llama 3xffn shardmap:  0.611614 ms      sizes: ('0.0625 MiB', '86.0 MiB', '86.0 MiB', '86.0 MiB')
bfloat16         Llama 3xffn gspmd:     0.596578 ms      sizes: ('0.0625 MiB', '86.0 MiB', '86.0 MiB', '86.0 MiB')
int8     Matmul replicated:     186.436 ms       sizes: ('1024.0 MiB', '1024.0 …
```

Add a script to measure speed of basic ops

---

jetstream_pt/ray_worker.py

Fix https://github.com/google/jetstream-pytorch/issues/150 without all_gather the kv cache

fix ray engine crashes on multihost

---

jetstream_pt/cli.py
jetstream_pt/engine.py
jetstream_pt/fetch_models.py
jetstream_pt/hf_tokenizer.py
jetstream_pt/layers.py
jetstream_pt/model_base.py
jetstream_pt/third_party/gemma/model.py
jetstream_pt/third_party/llama/model_exportable.py
jetstream_pt/third_party/mixtral/model.py
tests/test_quantization.py

```
python -m jetstream_pt.cli interactive --model_id meta-llama/Meta-Llama-3-8B-Instruct --quantize_weights=0
```

Add gemma support in better cli

---

README.md
jetstream_pt/cli.py
jetstream_pt/fetch_models.py
jetstream_pt/third_party/llama/model_exportable.py
pyproject.toml

Update README to refer to new CLI instead of old scripts. 
This README is not complete yet. But it will be completed with more details on flags before next release.

Update README for new CLI

---

jetstream_pt/attention_kernel.py
jetstream_pt/cache_manager.py
jetstream_pt/config.py
jetstream_pt/engine.py
jetstream_pt/environment.py
jetstream_pt/layers.py
jetstream_pt/page_attention_manager.py
tests/helpers.py
tests/test_attention_kernal.py
tests/test_kv_cache_manager.py
tests/test_page_attention.py

**Background:** 
PR #167 Added paged attention manager and kv cache manager. This PR supports end to end paged attention in JetStream. 
**Main Changes in this PR**
1. Added paged attention kernel in attention_kernel.py
2. Supported paged attention insert, decode in Engine.py
3. Refactor PageAttention manager 
4. Add unit test for kernel and manager
**Next Steps**
1. Tuning accuracy:  Current implement can output human readable output, but accuracy is low, only first few token are matches to dense attention
2. Improve performance: The kernel itself are almost same performance as dense attention. By applying bf16 calculation can boost the performance
4. Optimize the out jit compute
5. Elegant way to collect resource
6. Support quantization
7. Lazy cache update
**Current PR Output tokens …

Support End To End PagedAttention in JetStream

---

.github/workflows/offline_perf.yaml
benchmarks/run_offline.py
jetstream_pt/cli.py
jetstream_pt/fetch_models.py

* add a benchmark_offline mode for cli
* add ability to use random weights

Add offline perf ci

---

jetstream_pt/engine.py
jetstream_pt/page_attention_manager.py
tests/test_kv_cache_manager.py
tests/test_page_attention.py

Current Jax implementation is slow. The operation array is tiny, leverage NP compute in CPU can boost the performance.    
The performance improved >30x. Below are two benchmark comparison before vs after this PR: 
**Before**
`
Total: 16 ms,  fill_new_page: 3ms, get_page_token_indices: 13ms
`
**After** 
`
Total: 0.5 ms, to_nparray: 0.1 ms, fill_new_page: 0.01ms,  get_page_token_indices: 0.05 ms to_jax_array:0.3 ms
`

Switch to NP from Jax to  improve attention manager performance

---

jetstream_pt/cli.py
jetstream_pt/config.py
jetstream_pt/environment.py
jetstream_pt/quantize_model.py

Instead of internal_quantize_embedding_layer, add a flag that will allow to specify a list of layers. This can be a flexible solution to avoid quantizing a given list of layers, the Embedding layer but even few more if required.

feat: add quantize exclude layer flag

---

jetstream_pt/quantize_model.py

The quantization filter based on layer names did not work, because modules walk is done with the Module.apply method, that resolves names locally, so the "absolute" naming does not work. The fix just prepares a list out of the names before entering the loop, so the correct reference is captured.

Fix: correct quantization name filtering

---

jetstream_pt/cli.py
jetstream_pt/config.py

Adds jax_cache support https://github.com/AI-Hypercomputer/jetstream-pytorch/pull/187
```
root@jetstream-pytorch-server-596f4c646f-l9qxx:~# cd jax_cache/
root@jetstream-pytorch-server-596f4c646f-l9qxx:~/jax_cache# ls
jit_prefill-HASH 
jit_prefill-HASH
jit_prefill-HASH 
```

Add jax compilation cache config

---

docker/jetstream-pytorch-server/Dockerfile
docker/jetstream-pytorch-server/README.md
docker/jetstream-pytorch-server/jetstream_pytorch_server_entrypoint.sh
jetstream_pt/cli.py

Adds a Dockerfile and entrypoint script to build the jetstream-pytorch-server image for inference. This is to consolidate artifacts to build out the JetStream-PyTorch artifact in the jetstream-pytorch repository. Adding the Dockerfile here will help to build out our internal pipeline for model server image release, as right now, the components [here](https://github.com/GoogleCloudPlatform/ai-on-gke/tree/main/tutorials-and-examples/inference-servers/jetstream/pytorch/jetstream-pytorch-server) are referenced as part of a tutorial.

Add Dockerfile and entrypoint script for the jetstream-pytorch-server

---

README.md
jetstream_pt/cli.py
jetstream_pt/fetch_models.py
jetstream_pt/third_party/llama/model_args.py
jetstream_pt/third_party/llama/model_exportable.py

Added RoPE scaling support for Llama. This will enable the Llama 3.1, 3.2 and 3.3 (not vision) to be supported.

Llama 3.1 RoPE scaling

---

jetstream_pt/fetch_models.py
jetstream_pt/third_party/llama/model_exportable.py

Small change that allows directly using the recently released DeepSeek R1 Distils.
Tested on TPU v4-8 for "deepseek-ai/DeepSeek-R1-Distill-Llama-8B" and it worked.

Add deepseek distils as options
