AI-Hypercomputer/jetstream-pytorch

- jetstream_pt/__init__.py
- run_server.py
Makes the UX a little bit cleaner
> Move create_pytorch_engine to init.

- .github/workflows/unit_tests.yaml
- Add CICD for jetstream_pt unit tests with python code checks
> Add CICD for jetstream_pt unit tests

- tests/test_jax_torch.py
Add jax torch test to measure the computation diff between them in CPU.
> Add Jax torch test

- benchmarks/run_offline.py
- jetstream_pt/engine.py
- jetstream_pt/layers.py
- jetstream_pt/third_party/llama2/model_exportable.py
- jetstream_pt/third_party/llama2/tokenizer.py
- run_interactive.py
- run_server.py
This PR remove all unused import
> Remove unused import

- install_everything.sh
Unstall existing jax before install jax
> Unstall existing jax before install jax

- README.md
This PR add JetStream and MaxText link into readme.
> Add jetstream links

- README.md
> update create TPU VM link

- jetstream_pt/third_party/llama2/generation_original.py
- tests/test_llama_e2e.py
This PR add original llama prefill and decode. With original llama prefill and decode, it's easy to compare and test JetStream engine.
> Add original llama prefill and decode

- jetstream_pt/third_party/llama2/generation_original.py
- jetstream_pt/third_party/llama2/model_args.py
- jetstream_pt/third_party/llama2/model_exportable.py
- jetstream_pt/third_party/llama2/model_original.py
- jetstream_pt/third_party/llama2/tokenizer.py
This PR do cleanup and format third party code.
> Cleanup and format third party code

- benchmarks/analyze_sharegpt.py
- benchmarks/jax_test.py
- benchmarks/run_offline.py
This PR do cleanup and format benchmark code
> Cleanup and format benchmark code

- convert_checkpoints.py
- run_interactive.py
- run_server.py
This PR do cleanup and format main dir code
> Cleanup and format main dir code

- .github/workflows/unit_tests.yaml
> Enable pylint check

- benchmarks/.pylintrc
- benchmarks/__init__.py
- benchmarks/analyze_sharegpt.py
This pr fix pylint for micro benchmark.
> Fix pylint for micro benchmark

- benchmarks/run_offline.py
> Cleanup run_offline

- benchmarks/analyze_sharegpt.py
- benchmarks/run_offline.py
> Clean up benchmarks files

- jetstream_pt/.pylintrc
> Add .pylintrc

- jetstream_pt/cache_manager.py
After this PR:
--------------------------------------------------------------------
Your code has been **rated at 10.00/10** (previous run: 10.00/10, +0.00)
Before this PR: 
--------------------------------------------------------------------
Your code has been **rated at 6.53/10**
************* Module jetstream_pt.cache_manager
cache_manager.py:1:0: C0114: Missing module docstring (missing-module-docstring)
cache_manager.py:21:0: C0115: Missing class docstring (missing-class-docstring)
cache_manager.py:21:0: R0903: Too few public methods (1/2) (too-few-public-methods)
cache_manager.py:35:0: C0115: Missing class docstring (missing-class-docstring)
cache_manager.py:46:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return) …
> Cleanup cache_manager

- jetstream_pt/engine.py
After this PR:
> Your code has been **rated at 10.00/10** 
> our code has been **rated at 8.46/10**
> ************* Module jetstream_pt.engine
> engine.py:567:5: W0511: TODO load from files (fixme)
> engine.py:46:0: C0115: Missing class docstring (missing-class-docstring)
> engine.py:46:0: R0903: Too few public methods (0/2) (too-few-public-methods)
> engine.py:53:0: C0115: Missing class docstring (missing-class-docstring)
> engine.py:53:0: R0903: Too few public methods (0/2) (too-few-public-methods)
> engine.py:68:0: R0902: Too many instance attributes (12/7) (too-many-instance-attributes)
> engine.py:124:6: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
> engine.py:129:6: R1705: Unnecessary "else" after …
> Clean up engine

- jetstream_pt/environment.py
After this PR:
Your code has been **rated at 10.00/10** 
Your code has been **rated at 7.84/10** 
************* Module jetstream_pt.environment
environment.py:94:45: W0511: TODO (fixme)
environment.py:28:0: C0115: Missing class docstring (missing-class-docstring)
environment.py:28:0: R0902: Too many instance attributes (15/7) (too-many-instance-attributes)
environment.py:69:0: C0115: Missing class docstring (missing-class-docstring)
environment.py:69:0: R0902: Too many instance attributes (15/7) (too-many-instance-attributes)
environment.py:91:4: W0612: Unused variable 'Mesh' (unused-variable)
environment.py:117:2: C0116: Missing function or method docstring (missing-function-docstring)
environment.py:121:2: C0116: Missing function or method docstring …
> Cleanup environment

- jetstream_pt/quantize.py
After this PR:
Your code has been rated at 10.00/10 (previous run: 7.50/10, +2.50)
Your code has been **rated at 7.50/10**
************* Module jetstream_pt.quantize
quantize.py:18:0: C0116: Missing function or method docstring (missing-function-docstring)
quantize.py:26:0: C0116: Missing function or method docstring (missing-function-docstring)
> Cleanup quantize

- tests/.pylintrc
Add pylintrc to test dir and ignore Missing module docstring
> Add pylintrc to tests

- tests/test_engine.py
This PR disable test_engine check for now, will enable it after refactor the code.
> Disable test_engine check for now

- tests/test_llama_e2e.py
After this PR:
Your code has been **rated at 5.85/10**
************* Module tests.test_llama_e2e
test_llama_e2e.py:400:0: C0301: Line too long (117/100) (line-too-long)
test_llama_e2e.py:468:0: C0301: Line too long (117/100) (line-too-long)
test_llama_e2e.py:31:0: C0115: Missing class docstring (missing-class-docstring)
test_llama_e2e.py:33:2: C0116: Missing function or method docstring (missing-function-docstring)
test_llama_e2e.py:55:2: C0116: Missing function or method docstring (missing-function-docstring)
test_llama_e2e.py:61:16: W0212: Access to a protected member _model_arg of a client class (protected-access)
test_llama_e2e.py:57:4: W0612: Unused variable 'x' (unused-variable)
test_llama_e2e.py:81:2: C0116: Missing function …
> Clean up llama_e2e test

- convert_checkpoints.py
After this PR:
Your code has been **rated at 9.08/10**
************* Module jetstream-pytorch.convert_checkpoints
convert_checkpoints.py:370:0: C0301: Line too long (111/100) (line-too-long)
convert_checkpoints.py:219:0: R0912: Too many branches (15/12) (too-many-branches)
convert_checkpoints.py:291:27: C0207: Use input_ckpt_dir_str.rsplit('//', maxsplit=1)[-1] instead (use-maxsplit-arg)
convert_checkpoints.py:294:2: W0612: Unused variable 'bucket' (unused-variable)
convert_checkpoints.py:329:29: C0207: Use str(output_ckpt_dir).rsplit('//', maxsplit=1)[-1] instead (use-maxsplit-arg)
convert_checkpoints.py:328:2: W0612: Unused variable 'output_ckpt_dir_str' (unused-variable)
convert_checkpoints.py:352:4: C0415: Import outside …
> Fix convert checkpoint lint check

- jetstream_pt/engine.py
Use property instead of function
> Use property instead of function

- run_interactive.py
> Output all token text

- run_server_with_ray.py
This PR integrated with JetSteam and ray for interleave serving. Several points import to this PR:
1.  I'm defining a tpu_chip parameter to pass the devices info, the program will fetch device info from worker in future. 
2. Jax_padding must be set ad false, all the TPU are used by worker, it will throw error for any jax call outside of workers.
> Add run_server with ray for interleave serving 

- docs/add_hf_checkpoint_conversion.md
Follow up PR on https://github.com/google/jetstream-pytorch/pull/118
Add a guide on how to add support of HF ckpt for a model.
> Add guide on adding HF ckpt conversion support

- jetstream_pt/ray_worker.py
Fixes https://github.com/google/jetstream-pytorch/issues/150
> Fix Ray engine crash on multihost

- jetstream_pt/ray_engine.py
- run_ray_serve_interleave.py
Tested by running a gemma2 local test:
https://github.com/google/jetstream-pytorch?tab=readme-ov-file#gemma-7b
> Use kwargs to simplify the call sites a bit

- jetstream_pt/cli.py
- jetstream_pt/engine.py
It was supposed to print the received array but it was not doing it. Also, the type is now displayed.
cc: @qihqi
> fix: correct error message
